### ISSUE TITLE
멤버 시스템 완성하기

### ISSUE THREAD

**Issue by sukjuhong** [Kookmin-Contest/towork-backend#4]
현재 회원가입은 username, password만을 받아 진행한다.
이를 문제가 없도록 추가 구현해야한다.

**Comment by sukjuhong** [comment]
## 회원가입

- 가입할 이메일 받기
- 지정할 비밀번호 받기
- 사용자 이름 받기
- 생년월일 받기
- 사용자 이미지(?) 이건 잘 모르겠음 넣을지 말지 ⇒ 구분 쉽게할려면 넣는게 좋을지도
- 휴대폰 번호 받기

**Comment by hsukju00** [comment]
추가적으로 멤버 시스템을 확실하게 구현하겠음

**Comment by sukjuhong** [comment]
- [x] jwt exception handling
- [x] springdocs error response 작성
